% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{section}{-1}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaklines,
  commandchars=\\\{\}
}

\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={QRM II Graded Assignment (3)},
  pdfauthor={Group 18; Timo Bekkema, Younes Maach, Edo Ho,; David van der Beek, Daan van der Ree},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{QRM II Graded Assignment (3)}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Period 1, 2026}
\author{Group 18 \and Timo Bekkema, Younes Maach, Edo Ho, \and David van
der Beek, Daan van der Ree}
\date{08-10-2026}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

This assignment is to be completed in groups of 4-5. Further, all
students in your group need to be assigned to the same R tutorial group
(Friday's tutorial). You can sign yourself up for a group on Canvas.
Please do so
\textbf{before the start of your first R tutorial on Friday September 4th.}
You can use the Discussion Board in Canvas if you do not have a group
yet or if your group is incomplete.

The assignment has 5 parts, and each part corresponds to the course
material of that week (with the exclusion of week 6, for which there is
no R programming material).

You are supposed to hand in these assignments on Canvas at the following
dates:

\begin{itemize}
\tightlist
\item
  \textbf{Deadline 1} \emph{Sunday September 27th, at 23:59pm}: you are
  supposed to hand in weeks 1, 2, and 3 of this assignment. This will
  determine 18\% of your overall course grade
\item
  \textbf{Deadline 2} \emph{Sunday October 11th, at 23:59pm}: you are
  supposed to hand in weeks 4, and 5 of this assignment. This will
  determine 12\% of your overall course grade
\end{itemize}

The R tutorials (each Friday) will consist of two halves. During the
first half, you will discuss the tutorial exercises. These can be
downloaded separately from Canvas. During the second half, you can work
on this graded assignment within your own group. The purpose is that you
find out how to work with R for doing statistical analyses by yourself.
The tutorial exercises are meant to teach you basic commands to get you
started, but to answer the problem sets in this assignment, you might
need to research your own solutions, and use functions and commands not
described in the tutorial exercises. Learning how to solve your own
research problems is integral part of learning R. When you and your
group get stuck on how to approach an exercise, the hierarchy in finding
your way is as follows:

\begin{itemize}
\tightlist
\item
  use the concepts from the tutorial exercises;
\item
  use the cheat sheets available on Canvas;
\item
  use Google, YouTube, StackOverflow, or another website;
\item
  ask the teacher.
\end{itemize}

The use of generative AI is \textbf{not} permitted and may result in a
grade of 0. See the AI protocol in the course manual for details.

To answer the assignment, you can simply fill out this R markdown
document. There are designated places which you can fill with R code.
There are also designated spaces for you to answer each question. Often,
the structure of an answer will be as follows. First, you type the R
code in the designated box. This will show how you analyzed the data to
get the answer to the question. Below the box for the R code, you will
then summarize your answer to the question, i.e.~what are the
conclusions that you draw from the data analysis?

When handing in, you are supposed to submit this .Rmd file, and a
knitted version of this document. You can knit this document to pdf,
word, or html. Knitting to pdf requires you to have a .tex distribution
installed on your computer. Knitting to Word requires you to have Word
installed.

The exercises are designed such that you should be able to finish the
majority of them during the tutorial each week. If you are not able to
finish them fully during that time, you are expected to work on it in
your own time using the computers on campus or your own device. It is
best to meet as a group in-person when working together. If you want to
work remotely, github is a good platform to guarantee smooth
collaboration. Alternatively, you can email this .Rmd file back and
forth to one another as a group, but this is not recommended as it is
more cumbersome.

We encourage you to keep your code blocks, printing statements, and
final answers, as short as possible. In any case, there is a page limit
of 6 pages per week, which encompasses the total length of this document
which consists of the questions, your coding lines, and your answers.
When your answers to questions of the respective week exceed this page
limit, they will not be graded, resulting in zero points.

\section{Week 4}\label{week-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  There is an argument going on in the movie studio. \emph{Bob} claims
  that production budgets are getting out of hand, and that the studio
  should focus on making cheaper movies. \emph{Chantal} disagrees. She
  tells Bob that ``Every dollar we spend on movie production is more
  than offset by the increase in movie revenue'\,'.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Set up a regression model to test Chantal's claim, and estimate it.
  That is, estimate:
  \[\text{Revenue}_i=\beta_0+\beta_1 \text{Budget}_i +\varepsilon_i.\]
  Print a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Test for the null hypothesis that \(\beta_1 \leq 1\). Report the
  p-value and state your conclusion. \textbf{[2 points]}
\item
  Next, estimate the model
  \[\text{Log Revenue}_i=\beta_0+\beta_1 \text{Log Budget}_i +\varepsilon_i.\]
  When creating the variables Log Revenue and Log Budget, make sure that
  movies with a Revenue or Budget of zero are assigned the value ``NA''.
  Print a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Which model has better fit? The level-level model or the log-log
  model? Explain. \textbf{[2 points]}
\item
  Who do you think is correct? Bob or Chantal? What would you advise the
  movie studio to do? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#model genaamd "model4.1" is een lineair model, hoe beweegt omzet met gegeven budget. }
\NormalTok{model4}\FloatTok{.1} \OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ budget, }\AttributeTok{data =}\NormalTok{ movies)}
\FunctionTok{summary}\NormalTok{(model4}\FloatTok{.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = revenue ~ budget, data = movies)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -387813422  -39322110     610960    8901755  950609114 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -3.307e+06  4.636e+06  -0.713    0.476    
## budget       2.830e+00  8.798e-02  32.169   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 109900000 on 907 degrees of freedom
## Multiple R-squared:  0.5329, Adjusted R-squared:  0.5324 
## F-statistic:  1035 on 1 and 907 DF,  p-value: < 2.2e-16
\end{verbatim}

\textbf{Your Answer:}

The formula used,
\(\text{Revenue}_i = \beta_0 + \beta_1 \text{Budget}_i + \varepsilon_i\),
so does the revenue move proportionally with the added budget, so is it
profitable?

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#wat is de richtingscoefficient van het lineaire model(regressie model)}
\FunctionTok{coef}\NormalTok{(model4}\FloatTok{.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   (Intercept)        budget 
## -3.307163e+06  2.830122e+00
\end{verbatim}

\textbf{Your Answer:}

The answer gotten above is \(\beta_1 = 2.83\), meaning every dollar
spent on the budget on average, results in 2.83 revenue.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#geestimeerde helling b1 en SE vinden, na het vinden vna b1, heeft R 2 punten genomen, hoeveel blijven er over om te ondervinden of het klopt, test hoeveel SE meer dan 1 zijn}
\NormalTok{b1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(model4}\FloatTok{.1}\NormalTok{))[}\StringTok{"budget"}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{]}
\NormalTok{se1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(model4}\FloatTok{.1}\NormalTok{))[}\StringTok{"budget"}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{]}
\NormalTok{df1 }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(model4}\FloatTok{.1}\NormalTok{)}
\NormalTok{t\_stat }\OtherTok{\textless{}{-}}\NormalTok{ (b1 }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ se1}
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{{-}} \FunctionTok{pt}\NormalTok{(t\_stat, df1)}
\FunctionTok{print}\NormalTok{(p\_value)}\SpecialCharTok{/}\FunctionTok{print}\NormalTok{(b1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
## [1] 2.830122
\end{verbatim}

\begin{verbatim}
## [1] 0
\end{verbatim}

\textbf{Your Answer:}

b1 = 2.83, se1 = 0.088, so t\_stat = 20.8, and the p-value is basically
0. This means the probability of observing a slope as extreme as 2.83,
assuming the true slope is 1 or less, is practically zero, so we reject
the null hypothesis and conclude that Chantal is right for this dataset.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#een log = 0 kan niet, daarom die eruit filteren}
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{revenue))}
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{log\_budget }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{budget }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{budget))}
\NormalTok{model4}\FloatTok{.2} \OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget, }\AttributeTok{data =}\NormalTok{ movies)}
\FunctionTok{summary}\NormalTok{(model4}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log_revenue ~ log_budget, data = movies)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.8586  -0.6783   0.1831   0.8499   6.6344 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  2.56490    0.73689   3.481 0.000535 ***
## log_budget   0.88520    0.04311  20.535  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.479 on 627 degrees of freedom
##   (280 observations deleted due to missingness)
## Multiple R-squared:  0.4021, Adjusted R-squared:  0.4012 
## F-statistic: 421.7 on 1 and 627 DF,  p-value: < 2.2e-16
\end{verbatim}

\textbf{Your Answer:}

Movies with a revenue or budget of 0, are called NA before taking logs,
because log(0) is NA, 629 movies have both a positive revenue and
budget.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#wat is de rc van LM2}
\FunctionTok{coef}\NormalTok{(model4}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)  log_budget 
##   2.5648963   0.8852038
\end{verbatim}

\textbf{Your Answer:}

b1 = 0.885, meaning, a 1\% increase in budget, results in a 0.885\%
increase in revenue, so there are signs of diminishing returns, as a log
model with an elasticity below 1 is inelastic.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#using the anova formula (what google said) isnt optimal, because the variables are not the same. So the other easier option, using R\^{}2}
\FunctionTok{summary}\NormalTok{(model4}\FloatTok{.1}\NormalTok{)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5329176
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model4}\FloatTok{.2}\NormalTok{)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4021191
\end{verbatim}

\textbf{Your Answer:}

model4.1 has a R\^{}2 of 0.533 and model4.2 a R\^{}2 of 0.402, going off
of this, model4.1 is better. However, this method is not bullet proof,
because revenue is compared with log(revenue), and model4.1 has 909
movies, and model4.2 has 629. Both models take very large movies into
account, however because model4.1 uses revenue and budget in dollars and
model4.2 uses percentages, the large movies do not have so much impact
in model4.2. So, taking everything into account model4.2 gives a more
realistic outcome, that is the better fit.

\emph{step g}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#not needed}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Only looking at model4.1, chantal would have been right in my eyes, but
with the additional information of model4.2. I think Bob is more right,
but not fully, but because of the budget's diminishing returns it stops
being reasonable to invest somewhere. So my advice to the studio, be
somewhere in the middle, do not take such extreme positions. If you have
the money to invest in the budget, it is most likely profitable to do
so.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a scatterplot with log revenue on the y-axis, and log budget on
  the x-axis. Within the same scatterplot, draw a straight line which
  summarizes the association between the log of revenue and log of
  budget. \textbf{[3 points]}
\item
  Using the insights from the scatterplot, your linear model, and your
  data, find an example of a movie that vastly overperformed. That
  means, find a movie that had much more revenue than expected, given
  its budget. For this movie, report its log of revenue, its predicted
  log of revenue, and its residual. \textbf{[3 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Alpha = 0.5 omdat je het dan laat doorschijnen, zo zie je wanneer films dezelfde uitkomst hebben, se = FALSE, want R studio gaf een foutmelding. }
\FunctionTok{ggplot}\NormalTok{(movies, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ log\_budget, }\AttributeTok{y =}\NormalTok{ log\_revenue)) }\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+} 
\FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+} 
\FunctionTok{labs}\NormalTok{( }\AttributeTok{title =} \StringTok{"Log Revenue vs Log Budget"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Log Budget"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Log Revenue"}\NormalTok{) }\SpecialCharTok{+} 
\FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 280 rows containing non-finite outside the scale range
## (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 280 rows containing missing values or values outside the scale range
## (`geom_point()`).
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment3_files/figure-latex/unnamed-chunk-8-1.pdf}}

\textbf{Your Answer:}

The scatterplot is consistent with the previously found b1 value of
0.885, it shows a clear positive correlation between log budget and log
revenue. Furthermore showing a wide range of scatter around the average
line, thus showing budget cannot fully predict revenue.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#[] gebruik ik om iets te selecteren uit de dataset}
\NormalTok{movies\_complete }\OtherTok{\textless{}{-}}\NormalTok{ movies[}\FunctionTok{complete.cases}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{log\_revenue, movies}\SpecialCharTok{$}\NormalTok{log\_budget), ]}
\NormalTok{movies\_complete}\SpecialCharTok{$}\NormalTok{predicted\_log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model4}\FloatTok{.2}\NormalTok{, }\AttributeTok{newdata =}\NormalTok{ movies\_complete)}
\NormalTok{movies\_complete}\SpecialCharTok{$}\NormalTok{residual }\OtherTok{\textless{}{-}}\NormalTok{ movies\_complete}\SpecialCharTok{$}\NormalTok{log\_revenue }\SpecialCharTok{{-}}\NormalTok{ movies\_complete}\SpecialCharTok{$}\NormalTok{predicted\_log\_revenue}
\NormalTok{top\_movie }\OtherTok{\textless{}{-}}\NormalTok{ movies\_complete }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_max}\NormalTok{(residual, }\AttributeTok{n =} \DecValTok{1}\NormalTok{)}
\NormalTok{top\_movie[, }\FunctionTok{c}\NormalTok{(}\StringTok{"title"}\NormalTok{, }\StringTok{"log\_revenue"}\NormalTok{, }\StringTok{"predicted\_log\_revenue"}\NormalTok{, }\StringTok{"residual"}\NormalTok{, }\StringTok{"budget"}\NormalTok{, }\StringTok{"revenue"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 6
##   title     log_revenue predicted_log_revenue residual budget revenue
##   <chr>           <dbl>                 <dbl>    <dbl>  <dbl>   <dbl>
## 1 Tarnation        14.0                  7.33     6.63    218 1162014
\end{verbatim}

\textbf{Your Answer:}

The movie that has vastly overperformed percentage wise the most is
Tarnation, using 218 dollars to make 1,162,014 dollars. Tarnation has a
log revenue of 13.97, a predicted log revenue of 7.33, and a residual of
6.63, the largest in the entire dataset.

\section{Week 5}\label{week-5}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a frequency table of the variable genre. Which are the three
  genres that occur the most? \textbf{[2 points]}
\item
  Create a new variable called genre2. Make sure that the three most
  popular genres remain the same, but that all the other genres get
  categorized into one genre called ``Other''. Report a frequency table
  of this new variable genre2. \textbf{[2 points]}
\item
  Estimate an OLS model which has as dependent variable the log of
  revenue of a movie, and as independent variable the log of budget, a
  dummy for each level that genre2 can take, and the year of release.
  Show a summary of the resulting model and interpret each coefficient.
  \textbf{[4 points]}
\end{enumerate}

The movie studio that you work at is releasing a new movie in 2026. It
will be a Drama movie with a budget of 20,000,0000. It will have a
runtime of 120 minutes.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Estimate a model that is able to predict the revenue of this movie.
  Give its predicted revenue and include a 90\% prediction interval.
  \textbf{[5 points]}
\item
  Plot the residuals against various independent variables in the model.
  Do you find any evidence of heteroskedasticity? \textbf{[2 points]}
\item
  One executive at the studio wants to time the release of the movie to
  a specific month of the year such that they can maximize revenue.
  Another executive is of the opinion that the month in which the movie
  is released will not have a big impact on its revenue. Estimate a
  model that can test whether the month of release impacts the revenue
  of a movie. Use an appropriate hypothesis test to test whether month
  of release matters. What would you advise the movie studio regarding
  the timing of the release of the movie? \textbf{[5 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Frequentie tabel van de genre variabel}
\NormalTok{genre\_freq\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{genre)}
\CommentTok{\# Sorteer om de top 3 te vinden}
\FunctionTok{sort}\NormalTok{(genre\_freq\_table, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    Drama   Comedy Thriller 
##      455      195      127
\end{verbatim}

\textbf{Your Answer:}

The three most occurring genres in the dataset are Drama, Comedy and
Thriller.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Creëer een variabel die Drama, Comedy en Thriller laat zien en de rest bij elkaar voegt onder \textquotesingle{}Other\textquotesingle{}}
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{genre2 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{genre }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Drama"}\NormalTok{, }\StringTok{"Comedy"}\NormalTok{, }\StringTok{"Thriller"}\NormalTok{),}
\NormalTok{                        movies}\SpecialCharTok{$}\NormalTok{genre,}
                        \StringTok{"Other"}\NormalTok{)}
\CommentTok{\# Laat de tabel zien met de nieuwe variabele}
\FunctionTok{table}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{genre2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Comedy    Drama    Other Thriller 
##      195      455      132      127
\end{verbatim}

\textbf{Your Answer:}

The new variable `genre2' retains Drama, Comedy and Thriller, while
compacting all remaining genres into the `Other' category.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Alle 0en als NA\textquotesingle{}s weergeven}
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{revenue))}
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{log\_budget }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{budget }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{budget))}

\CommentTok{\# Schat OLS model}
\NormalTok{model\_c }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(genre2) }\SpecialCharTok{+}\NormalTok{ release\_year, }\AttributeTok{data =}\NormalTok{ movies)}
\FunctionTok{summary}\NormalTok{(model\_c)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log_revenue ~ log_budget + factor(genre2) + release_year, 
##     data = movies)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.8744  -0.6599   0.1682   0.7996   6.4989 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)            -24.607849  18.022645  -1.365    0.173    
## log_budget               0.863306   0.044720  19.305   <2e-16 ***
## factor(genre2)Drama     -0.096063   0.153515  -0.626    0.532    
## factor(genre2)Other      0.234793   0.204194   1.150    0.251    
## factor(genre2)Thriller   0.023238   0.191402   0.121    0.903    
## release_year             0.013741   0.008977   1.531    0.126    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.476 on 623 degrees of freedom
##   (280 observations deleted due to missingness)
## Multiple R-squared:  0.4079, Adjusted R-squared:  0.4032 
## F-statistic: 85.85 on 5 and 623 DF,  p-value: < 2.2e-16
\end{verbatim}

\textbf{Your Answer:} Intercept(-24.6078): The intercept represents the
expected log revenue of a baseline comedy movie released in the year 0,
with a total production budget of \$1. Because a budget of \$1 and a
release year of 0 are impossible, this coefficient has no meaningful
economic interpretation.

Log\_budget (0.8633): Because both budget and revenue are
log-transformed, this represents the elasticity. A 1\% increase in the
production budget leads to an approximate 0.86\% increase in revenue,
whilst holding other variables constant.

factor(genre2): The coefficients represent the expected difference in
log revenue compared to the baseline Comedy category. In a log-linear
model, the percentage effect is calculated as 100 * (exp(coefficient) -
1). For example, movies in the ``Other'' category have a coefficient of
0.2348, meaning approximately 26.5\% higher expected revenue than
comedies when holding budget and year constant. Similarly, Drama and
Thriller have approximately 9.1\% lower and 2.3\% higher revenues
relative to comedy, respectively

Release\_year (0.0137): Each successive year of release is associated
with an approximate 1.37\% increase in revenue, holding all other
factors constant.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Runtime in model zetten om specifieke film te schatten}
\NormalTok{model\_d }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(genre2) }\SpecialCharTok{+}\NormalTok{ release\_year }\SpecialCharTok{+}\NormalTok{ runtime, }\AttributeTok{data =}\NormalTok{ movies)}

\CommentTok{\# Dataframe maken voor 2026 drama movie (met budget van 20,000,000)}
\NormalTok{new\_movie }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{log\_budget =} \FunctionTok{log}\NormalTok{(}\DecValTok{20000000}\NormalTok{),}
  \AttributeTok{genre2 =} \StringTok{"Drama"}\NormalTok{,}
  \AttributeTok{release\_year =} \DecValTok{2026}\NormalTok{,}
  \AttributeTok{runtime =} \DecValTok{120}
\NormalTok{)}

\CommentTok{\# Schat log omzet met 90\% prediction interval}
\NormalTok{pred\_log }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_d, }\AttributeTok{newdata =}\NormalTok{ new\_movie, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{, }\AttributeTok{level =} \FloatTok{0.90}\NormalTok{)}

\CommentTok{\# Exponenteer om resultaten in USD te krijgen}
\FunctionTok{exp}\NormalTok{(pred\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit     lwr       upr
## 1 49301798 4262893 570191984
\end{verbatim}

\textbf{Your Answer:}

After building a model that accounts for runtime, the predicted revenue
for this 2026 Drama movie is around \$49.3 million. The 90\% prediction
interval ranges from \$4.26 million to \$570.2 million, showing a high
variance in movie revenues.

*Note: The question mentions a budget of ``20,000,0000''. Course
coordinator Aglio confirmed that this is supposed to be \$20 million.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot de residuals tegen fitted values om heteroskedasticity te checken}
\FunctionTok{plot}\NormalTok{(model\_d}\SpecialCharTok{$}\NormalTok{fitted.values, }\FunctionTok{resid}\NormalTok{(model\_d),}
     \AttributeTok{main =} \StringTok{"Residuals vs. Fitted Values"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Fitted Values"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Residuals"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment3_files/figure-latex/unnamed-chunk-14-1.pdf}}

\textbf{Your Answer:}

By plotting the residuals against the fitted values (or other
independent variables), we can visually inspect the spread. If the
spread of the residuals widens or narrows significantly as fitted values
increase (a funnel shape) this provides evidence of heteroskedasticity.

This plot shows clear evidence of heteroskedasticity because the
vertical variance of the residuals is not constant. The errors are
highly dispersed for fitted values between 14 and 17 but cluster more
tightly as fitted values approach 20, perfectly matching the `funnel
shape'.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Schat een nieuw model met release\_month als een categorisch variabel}
\NormalTok{model\_f }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(genre2) }\SpecialCharTok{+}\NormalTok{ release\_year }\SpecialCharTok{+}\NormalTok{ runtime }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(release\_month), }\AttributeTok{data =}\NormalTok{ movies)}

\CommentTok{\# Voer een F{-}test (anova) uit die de twee modellen vergelijkt}
\FunctionTok{anova}\NormalTok{(model\_d, model\_f)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: log_revenue ~ log_budget + factor(genre2) + release_year + runtime
## Model 2: log_revenue ~ log_budget + factor(genre2) + release_year + runtime + 
##     factor(release_month)
##   Res.Df    RSS Df Sum of Sq      F Pr(>F)
## 1    622 1346.7                           
## 2    611 1320.1 11    26.626 1.1203 0.3422
\end{verbatim}

\textbf{Your Answer:}

The F-test comparing the model with and without the release\_month
variable has a p-value of 0.3422. Because this p-value is greater than
the standard 0.05 significance level, it proves that the release month
does not have a statistical significant impact on a movie's revenue.
Therefore, I would advise the studio that trying to time the release to
a specific month to maximize revenue is not supported by this.

\end{document}
